name: Pipeline - Subida Aliv

on:
  schedule:
    - cron: "0 14 * * *"   # 9:00am Peru (UTC-5)
  workflow_dispatch: {}

jobs:
  run:
    uses: ./.github/workflows/_pipeline-run.yml
    with:
      fase: subida_aliv
    secrets: inherit
